### ISSUE TITLE
Extending

### ISSUE THREAD

**Issue by ghost** [mjl-/duit#6]
This is awesome.
The tab for mouse focus is a great way to solve a tough ux thing.

I am going to try to build a little bit with this.

It's using opengl under the hood or SDL ? I ask because I am trying to imagine how tough the Windows code will be :)

Anyway great stuff !!

**Comment by Happy-Ferret** [comment]
Not the maintainer (obviously), but from the looks of it it's neither using SDL nor OpenGL.
Just Plan9 From Userspace's ``devdraw`` implementation, which renders either to X11 or MacOS Quartz.

**Comment by ghost** [comment]
thanks.

Was wondering about the x11 and quartz.
Thats likely to be a real pain to port to Windows.
Bit of a bummer...  i saw something from BurntSushi about this that might
help

https://github.com/BurntSushi/xgb

**Comment by ghost** [comment]
also i see that its needs plan 9. i dont see windows support there either.

**Comment by Happy-Ferret** [comment]
It really shouldn't be much of a pain, as per @mjl- 's own [blog post](https://www.ueber.net/who/mjl/blog/p/duit-developer-ui-toolkit/).

You'd just need to replace ``9fans.net/go/draw`` with something that talks to the native graphics subsystem of the respective OS. Alternatively, one could most likely also use whatever ``drawterm`` and ``Inferno`` are using under the hood, since both work under Windows.

And yea. It does need plan9port. That's where ``devdraw`` and the ``plumber`` originate from.

Lastly, it's worth noting that ``duit`` does work under Windows 10 already. Provided you use [WSL](https://docs.microsoft.com/en-us/windows/wsl/install-win10) (the Windows Subsystem for Linux) in combination with [Xming](https://sourceforge.net/projects/xming/).

**Comment by mjl-** [comment]
indeed, the plan is not to keep requiring x11 on windows.

**Comment by Happy-Ferret** [comment]
If anything, GNU/Linux should be more of a challenge.
Given the fragmentation, in the future you'd either have to depend on XWayland, port it to native Wayland or to Arcan.

**Comment by mjl-** [comment]
closing old issue. just another note: i did try to get rid of devdraw quite some time ago. it seems possible on win32, x11, wayland, plan9. i didn't see a way to do it on macos (native libs and cgo seems required there). code wasn't finished.
